site:
  name: 枢衡の巢
  icon: 'https://picbed-1304952903.cos.ap-beijing.myqcloud.com/pic/blog202302030251122.png'
  greet: 你好，我是枢衡！
  description: 一只小乌鸦的学习日记~
  socialLinks: 
    github||fab fa-github: https://github.com/charles-hsuz
    Email||fas fa-envelope: mailto:charles_hsu@qq.com
    PWA||fas fa-puzzle-piece: 'javascript:void(0);'
  followMe: https://github.com/charles-hsuz
  
title:
  normal: 枢衡の巢
  focusless: (つェ⊂)我藏好了哦~
  delay: 300

menu:
  首页: / || fas fa-home
  文章||fas fa-archive:
    时间轴: /archives/ || fa-solid fa-clock
    标签: /tags/ || fas fa-tags
    分类: /categories/ || fas fa-folder-open
  清单||fa fa-heartbeat:
    个人动态: /bb/ || fa-solid fa-compass
    小工具: /tools/ || fa-solid fa-toolbox
  我的||fa-solid fa-user:
    友链: /link/ || fas fa-link
    关于: /about/ || fas fa-heart

nav:
  logo: https://picbed-1304952903.cos.ap-beijing.myqcloud.com/pic/blog202302030251122.png
  display_title: true
  fixed: true # fixed navigation bar

inject:
  head:
    - 
  body:
    -

sidebar:
  position: left
  cards:
    author: true
    articles: true
    categories: true
    tags: true
    archives: true
    webinfo: true

footer:
  buttons:
    Email||fa-solid fa-envelope||blue: "mailto:charles_hsu@qq.com"
    QQ||fa-brands fa-qq||light-blue: "tencent://Message/?Uin=1191393280&websiteName=q-zone.qq.com&Menu=yes"
    top||fa-solid fa-angle-up||gray: "#"
    github||fab fa-github||black: "https://github.com/charles-hsuz"
    CSDN||fa-solid fa-copyright||red: "https://blog.csdn.net/CharlesHsuu?type=blog"
  menu:
    直达:
      - 我的主页||/
      - 个人动态||/bb
      - 随机文章||/random/index.html
    分类:
      - 学习笔记||/catogories/学习笔记/
      - 算法教程||/catogories/算法教程/
      - 刷题笔记||/catogories/刷题笔记/
      - 语法教程||/catogories/语法教程/
      - 工具分享||/catogories/工具分享/
    关于:
      - 关于我||/about
      - 博客统计||/chart
      - 文章归档||/archives
    友链:
      - 在这里||/link
      - 广告位招租||mailto:charles_hsu@qq.com
    协议:
      - 隐私协议||/privacy
      - Cookie||/cookie
      - 版权协议||/cc