site:
  name: 枢衡の巢
  icon: 'https://picbed-1304952903.cos.ap-beijing.myqcloud.com/pic/blog202302030251122.png'
  
title:
  normal: 枢衡の巢
  focusless: (つェ⊂)我藏好了哦~
  delay: 300

menu:
  首页: / || fas fa-home
  文章||fas fa-archive:
    时间轴: /archives/ || fa-solid fa-clock
    标签: /tags/ || fas fa-tags
    分类: /categories/ || fas fa-folder-open
  清单||fa fa-heartbeat:
    个人动态: /bb/ || fa-solid fa-compass
    小工具: /tools/ || fa-solid fa-toolbox
  我的||fa-solid fa-user:
    友链: /link/ || fas fa-link
    关于: /about/ || fas fa-heart

nav:
  logo: https://picbed-1304952903.cos.ap-beijing.myqcloud.com/pic/blog202302030251122.png
  display_title: true
  fixed: true # fixed navigation bar

inject:
  head:
    - 
  body:
    -

footer:
  buttons:
    Email||fa-solid fa-envelope||blue: "mailto:charles_hsu@qq.com"
    QQ||fa-brands fa-qq||light-blue: "tencent://Message/?Uin=1191393280&websiteName=q-zone.qq.com&Menu=yes"
    top||fa-solid fa-angle-up||gray: "#"
    github||fab fa-github||black: "https://github.com/charles-hsuz"
    CSDN||fa-solid fa-copyright||red: "https://blog.csdn.net/CharlesHsuu?type=blog"